### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by muammar** [gerardmassey/audiodevice#1]
When I try to execute it I get error above.

**Comment by mattPiratt** [comment]
same here. After upgrade to MacOS Catalina

**Comment by mattPiratt** [comment]
I have found version here that works on Catalina https://www.file-upload.net/download-13712395/audiodeviceX64.zip.html (taken from comments here http://whoshacks.blogspot.com/2009/01/change-audio-devices-via-shell-script.html )

**Comment by dploeger** [comment]
Yeah, file-upload.net also delivers some creepy additional thing when downloading it. I've uploaded it to my Gdrive to avoid this:

https://drive.google.com/file/d/1FYseZn4viEhr4TRNDfFjeSP-1b-ssguu/view?usp=sharing

Also, under 10.15 you need to use the usual Right-click/Right-Click on open/Allow trick to have it executable, because it is unsigned.

@gerardmassey Maybe you could add this as an asset to the 1.0-release?

**Comment by gerardmassey** [comment]
> Yeah, file-upload.net also delivers some creepy additional thing when downloading it. I've uploaded it to my Gdrive to avoid this:
> 
> https://drive.google.com/file/d/1FYseZn4viEhr4TRNDfFjeSP-1b-ssguu/view?usp=sharing
> 
> Also, under 10.15 you need to use the usual Right-click/Right-Click on open/Allow trick to have it executable, because it is unsigned.
> 
> @gerardmassey Maybe you could add this as an asset to the 1.0-release?

Done!

**Comment by dploeger** [comment]
Awesome, thanks.
